api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('users/', views.user_list, name='user-list'),
    path('email-login/', views.email_login, name='email-login'),
    path('user-registration/', views.user_registration, name='user-registration'),
    path('get-user-projects/<str:email>/', views.get_user_projects, name='get_user_projects'),
    path('project-details/<int:project_id>/<str:email>/', views.get_project_details, name='get_project_details'),
    path('edit-step/<int:step_id>/', views.edit_step, name='edit-step'),
    path('logout/<str:email>/', views.logout_view, name='logout'),
    path('get_step_details/<int:step_id>/', views.get_step_details, name='get-step-details'),
    path('is_user_project_manager/<str:email>/', views.is_user_project_manager, name='is_user_project_manager'),
    path('update_project_from_smartsheet/', views.update_project_from_smartsheet, name='update_project_from_smartsheet'),


] 

events/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("api/", include('api.urls')),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.landing_page, name="landing_page"),
    path("home/", views.home, name="home"),
    path("login/", views.user_login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("create/", views.create_project, name="create_project"),
    path("workers/", views.workers, name="workers"),
    path("create_users/", views.create_users, name="create_users"),
    path("step/<int:step_id>/", views.step_details, name="step_details"),
    path("project/<int:project_id>/", views.project_details, name="project_details"),
    path("edit/<int:project_id>/", views.edit_project, name="edit_project"),
    path("edit_step/<int:step_id>/", views.edit_step, name="edit_step"),
    path(
        "delete_project/<int:project_id>/", views.delete_project, name="delete_project"
    ),
    path(
        "duplicate/<int:project_id>/", views.duplicate_project, name="duplicate_project"
    ),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),

]

home/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.contrib.auth import get_user_model
from django.conf import settings

User = settings.AUTH_USER_MODEL


# Create your models here.


class MyUserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault("is_admin", True)
        return self.create_user(username, email, password, **extra_fields)


class MyUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(unique=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_project_manager = models.BooleanField(default=False)
    manager = models.CharField(max_length=255, blank=True, null=True)
    assigned_steps_count = models.BigIntegerField(default=0)
    completed_steps_count = models.BigIntegerField(default=0)
    progress_percentage = models.BigIntegerField(default=0)

    objects = MyUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    class Meta:
        permissions = [
            ("can_create_users", "Can create new users"),
        ]



class Project(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True, default="")
    equipment = models.TextField(null=True, blank=True, default="")
    vehicle = models.TextField(null=True, blank=True, default="")
    todays_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.name


class Step(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True, default="") 
    description = models.TextField(null=True, blank=True, default="")
    todays_date = models.DateField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    assigned_to = models.CharField(max_length=100, null=True)
    file = models.FileField(upload_to="static/steps/", null=True, blank=True)
    file2 = models.FileField(upload_to="static/steps/", null=True, blank=True)
    file3 = models.FileField(upload_to="static/steps/", null=True, blank=True)
    file4 = models.FileField(upload_to="static/steps/", null=True, blank=True)
    sign_sheet = models.FileField(upload_to="static/steps/", null=True, blank=True)

    def __str__(self):
        return self.assigned_to

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import MyUser, Step, Project
from django.contrib.auth import authenticate
from datetime import date


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description", "todays_date", "equipment", "vehicle"]


class StepForm(forms.ModelForm):
    assigned_to = forms.CharField(max_length=100)

    class Meta:
        model = Step
        # fields = ["name", "description", "todays_date", "file", "sign_sheet"]
        fields = [
            "description",
            "todays_date",
            "file",
            "file2",
            "file3",
            "file4",
            "sign_sheet",
        ]

        widgets = {"todays_date": forms.DateInput(attrs={"type": "date"})}


class StepDoneForm(forms.ModelForm):
    class Meta:
        model = Step
        fields = [
            "is_done",
            "file",
            "file2",
            "file3",
            "file4",
            "sign_sheet",
            "description",
        ]


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = MyUser
        fields = ["username", "email", "password1", "password2"]


class EmailLoginForm(AuthenticationForm):
    username = forms.EmailField(label="Email")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({"autofocus": True})


class ManagerCreatesUserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = MyUser
        fields = ["username", "email", "password1", "password2"]

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import (
    EmailLoginForm,
    UserRegistrationForm,
    StepForm,
    ProjectForm,
    ManagerCreatesUserForm,
    StepDoneForm,

)
from django.contrib.auth import authenticate, login, logout
from .models import Project, Step
from django import forms
from .models import MyUser
from django.forms import modelformset_factory
from django.forms.models import model_to_dict

# For emails
from email.message import EmailMessage
import ssl, smtplib
from . import config
# Create your views here.


def landing_page(request):
    return render(request, "landing_page.html")

def home(request):
    context = {}
    user = request.user
    if user.is_authenticated:
        if user.is_project_manager:

            projects = (
                Project.objects.filter(author=user, step__isnull=False)
                .order_by("-id")  # Reverse order by project ID
                .distinct()
                .all()
            )

        else:
            manager = MyUser.objects.get(email=user.manager)
            projects = (
                Project.objects.filter(
                    step__assigned_to=user.username,  # Filter projects based on steps assigned to the user
                    step__project__author=manager,  # Additionally, the project's author must be the user's manager
                )
                .distinct()
                .prefetch_related("step_set")
                .order_by("-id")
            )
        context["projects"] = projects
        context["user"] = user
        return render(request, "home.html", context=context)
    else:
        return redirect("login")



def create_users(request):
    user = request.user
    if request.method == "POST":
        form = ManagerCreatesUserForm(request.POST)
        if form.is_valid():
            # Create the new user without using the form's save() method
            new_worker_username = form.cleaned_data["username"]
            new_worker_email = form.cleaned_data["email"]
            new_worker_password = form.cleaned_data["password1"]
            new_user = MyUser(
                username=new_worker_username,
                email=new_worker_email,
                manager=user.email,  # Set the manager for the new user
            )
            new_user.set_password(new_worker_password)
            new_user.save()  # Redirect to the same page after user creation

            # My email configuration
            email_sender = config.EMAIL_SENDER
            email_password = config.EMAIL_PASSWORD

            email_receiver = user.email
            print(user.email)


            subject = f" Facilo | Worker Account Created"

            body = f"""\
            Worker account for {new_worker_username}
            Worker email: {new_worker_email}
            Worker password: {new_worker_password}
        
    
            Software provided by Facilo"""


            em = EmailMessage()

            em["From"] = email_sender
            em["To"] = f"{email_receiver}, dterrero10@gmail.com "
            em["subject"] = subject
            em.set_content(body)

            context = ssl.create_default_context()

            #  Send Email
            with smtplib.SMTP_SSL('smtpout.secureserver.net', 465, context=context) as smtp:
                smtp.login(email_sender, email_password)
                smtp.sendmail(email_sender, email_receiver, em.as_string())

            return redirect("home")
    else:
        form = ManagerCreatesUserForm()
    # Fetch non-project manager users
    return render(request, "create_users.html", {"form": form})


def user_login(request):
    if request.user.is_authenticated:
        return redirect("home")

    if request.method == "POST":
        form = EmailLoginForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                # Redirect to a success page or perform any other desired actions
                return redirect("home")  # Replace 'home' with your desired URL name
            else:
                # Authentication failed
                form.add_error(None, "Invalid email or password.")
    else:
        form = EmailLoginForm()

    return render(request, "login.html", {"form": form})


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)  # Don't save the user yet
            user.is_project_manager = True  # Set the user as a project manager
            user.save()  # Now save the user with the updated is_project_manager field
            return redirect("login")  # Name used in urls.py
    else:
        form = UserRegistrationForm()

    context = {"form": form}
    return render(request, "register.html", context)


def logout_view(request):
    logout(request)
    return redirect("home")


def step_details(request, step_id):
    user = request.user
    context = {}

    step = get_object_or_404(Step, id=step_id)

    # Get the project ID from the related Project object
    project_id = step.project.id

    # Create an instance of the StepDoneForm with the current step's data
    step_done_form = StepDoneForm(instance=step)

    if request.method == "POST":
        # Check if the user submitted the StepDoneForm

        if "step_done_form" in request.POST:
            step_done_form = StepDoneForm(request.POST, request.FILES, instance=step)
            if step_done_form.is_valid():
                step_done_form.save()
                return redirect("project_details", project_id=project_id)

    context["user"] = user
    context["step"] = step
    context["step_done_form"] = step_done_form
    context["project_id"] = project_id  # Pass the project ID to the template
    return render(request, "step_details.html", context)


def create_project(request):
    user = request.user
    users = MyUser.objects.filter(manager=user.email)
    StepFormSet = forms.formset_factory(
        form=StepForm, extra=0, min_num=1
    )  # min_num is set to 1 to have at least one step
    if request.method == "POST":
        project_form = ProjectForm(request.POST)
        formset = StepFormSet(request.POST, request.FILES, prefix="steps")
        print(formset)

        if project_form.is_valid() and formset.is_valid():
            project = project_form.save(commit=False)

            # Set the author (manager) to the currently logged-in user
            project.author = request.user

            # Save the project to the database with the author assigned
            project.save()

            for form in formset:
                step = form.save(commit=False)
                step.project = project
                assigned_to = form.cleaned_data.get(
                    "assigned_to"
                )  # Get the value from the dropdown
                step.assigned_to = assigned_to
                step.save()

            return redirect("home")  # Redirect to home page
    else:
        project_form = ProjectForm()
        formset = StepFormSet(prefix="steps")  # Queryset is set to an empty list

    total_form_count = formset.total_form_count()  # Calculate total form count
    return render(
        request,
        "create_project.html",
        {
            "project_form": project_form,
            "formset": formset,
            "users": users,
            "total_form_count": total_form_count,  # Pass total form count to the template
        },
    )



def project_details(request, project_id):
    context = {}
    user = request.user
    context["user"] = user

    # Get the project instance using the project_id from the URL
    project = get_object_or_404(Project, id=project_id)

    # Fetch the steps associated with the project
    steps = project.step_set.all()

    context["project"] = project
    context["steps"] = steps

    return render(request, "project_details.html", context)


def edit_project(request, project_id):
    user = request.user
    users = MyUser.objects.filter(manager=user.email)
    project = get_object_or_404(Project, id=project_id)
    steps = project.step_set.all()

    StepFormSet = forms.formset_factory(form=StepForm, extra=0, min_num=1)

    if request.method == "POST":
        project_form = ProjectForm(request.POST, instance=project)
        formset = StepFormSet(request.POST, request.FILES, prefix="steps")

        if project_form.is_valid() and formset.is_valid():
            project = project_form.save(commit=False)

            # Save the project to the database with the author assigned
            project.save()

            # Remove the first step from the queryset and delete it
            if steps.exists():
                first_step = steps.first()
                first_step.delete()

            for form in formset:
                step = form.save(commit=False)
                step.project = project
                assigned_to = form.cleaned_data.get("assigned_to")
                step.assigned_to = assigned_to
                step.save()

            return redirect("home")  # Redirect to the home page

    else:
        project_form = ProjectForm(instance=project)
        formset = StepFormSet(prefix="steps")

    total_form_count = formset.total_form_count()

    return render(
        request,
        "edit_project.html",
        {
            "project_form": project_form,
            "formset": formset,
            "users": users,
            "steps": steps,
            "total_form_count": total_form_count,
            "project": project,
        },
    )


def edit_step(request, step_id):
    user = request.user

home/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Facilo{% block title %}{% endblock %}</title>
    <link rel="preload" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"></noscript>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link alt="Facilo" href="/static/logo.png" type="images/jpg" rel="icon">
    <style>
        p {
            font-family: 'DM Sans', sans-serif;
        }
    </style>
    {% block head %}{% endblock %}
</head>
<body>
    {% comment %} Importing GetBootstrapped {% endcomment %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    {% comment %} Icons SVG {% endcomment %}
    {% block content %}{% endblock %}
    {% block script %}{% endblock %}
</body>
</html>

home/templates/create_project.html
{% extends 'base.html' %}

{% block content %}
<!-- create_project.html -->
<div class="navbar">
    <div>
        {% if user.is_authenticated %}
            <a href="/logout/">Logout</a>
            <a href="/create/">New Project</a>
            <a href="/create_users/">Create Worker</a>
        {% else %}
            <a href="/login/">Login</a>
        {% endif %}
    </div>
    <a href="/home/"><p>{{ user.username }}</p></a>
</div>

<div class="container register-form-container" style="background-color: #333; color: #fff;">
    <h3>Project</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
                <p>
            <label for="id_name">Customer name, address and contact</label>
            <input type="text" name="name" maxlength="100" required id="id_name">
            
            
          </p>
        
          
          <p>
            <label for="id_description">Description of work required for completion</label>
            <textarea name="description" cols="40" rows="5" required id="id_description">
        </textarea>
            
            
          </p>

          <p>
            <label for="id_equipment">Equipment & Supplies Needed</label>
            <textarea name="equipment" cols="40" rows="5" required id="id_equipment">
        </textarea>
            
            
          </p>
          <p>
            <label for="id_vehicle">Vehicle Needed</label>
            <textarea name="vehicle" cols="40" rows="3" required id="id_vehicle">
        </textarea>
            
            
          </p>
          
          <p>
            <label for="id_todays_date">Today's Date</label>
            <input type="date" name="todays_date" required id="id_todays_date">
            
            
              
            
          </p>

        <h3>Assignments</h3>
        <div id="step-forms">
            {{ formset.management_form }}

            {% for form in formset %}
            {% comment %} <div class="form-group">
                <label for="{{ form.name.id_for_label }}">Assignment Name:</label>
                {{ form.name }}
            </div> {% endcomment %}

                        <!-- Change the input field to a select element for "Assigned To" field -->
            <div class="form-group">
                <label for="{{ form.prefix }}-assigned_to">Assigned to:</label>
                <select name="{{ form.prefix }}-assigned_to" id="{{ form.prefix }}-assigned_to" class="form-control">
                    <option value="" selected disabled>Choose a worker</option>
                    {% for user in users %}
                    <option value="{{ user.username }}">{{ user.username }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="{{ form.todays_date.id_for_label }}">Today's Date</label>
                {{ form.todays_date }}
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label for="{{ form.file.id_for_label }}">Picture 9am:</label>
                    {{ form.file }}
                </div>
                <div class="form-group">
                    <label for="{{ form.file2.id_for_label }}">Picture 11am:</label>
                    {{ form.file2 }}
                </div>
                <div class="form-group">
                    <label for="{{ form.file3.id_for_label }}">Picture 1pm:</label>
                    {{ form.file3 }}
                </div>
                <div class="form-group">
                    <label for="{{ form.file4.id_for_label }}">Picture 4pm:</label>
                    {{ form.file4 }}
                </div>
            </div>

            <div class="form-group">
                <label for="{{ form.sign_sheet.id_for_label }}">Signed job sheet:</label>
                {{ form.file }}
            </div>

            <div class="form-group">
                <label for="id_steps-0-description">Additional Comments</label>
                <textarea name="steps-0-description" cols="40" rows="10" id="id_steps-0-description"> </textarea>
            </div>


            {% endfor %}
        </div>

        <button type="button" id="add-step-btn" class="btn btn-primary">Add Worker</button>
        <input type="submit" value="Create Project" class="btn btn-primary">
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    let formIdx = {{ formset.total_form_count }};
    const addStep = document.getElementById("add-step-btn");

    addStep.addEventListener("click", updateID);
    // Function to add a new step form
    function addStepForm(prefix) {
        const emptyFormEl = document.getElementById("empty-form").cloneNode(true);
        // Update the ID of the new "empty-form"
        emptyFormEl.id = `emptyform${formIdx}`;
        emptyFormEl.innerHTML = emptyFormEl.innerHTML.replace(/__prefix__/g, formIdx);
        emptyFormEl.style.display = "block";
        emptyFormEl.querySelectorAll("select").forEach((select) => {
            select.id = select.id.replace(/__prefix__/g, formIdx);
            select.name = select.name.replace(/__prefix__/g, formIdx);
        });
        document.getElementById("step-forms").appendChild(emptyFormEl);
        // Get today's date
        var today = new Date();
    
        // Format the date to be used in the input fields
        var dd = String(today.getDate()).padStart(2, '0');
        var mm = String(today.getMonth() + 1).padStart(2, '0'); // January is 0!
        var yyyy = today.getFullYear();
    
        today = yyyy + '-' + mm + '-' + dd;
    
        // Find all input elements with ID containing "due_date"
        var todaysDateInputs = document.querySelectorAll('input[id*="todays_date"]');
    
        // Set the default value for each found element
        todaysDateInputs.forEach(function(input) {
        input.value = today;
        });
    }

    // Add step button click event
    function updateID() {
        addStepForm("steps");
        formIdx++;
        $('#id_steps-TOTAL_FORMS').val(formIdx);
    }
</script>
<script>
    // Get today's date
    var today = new Date();
  
    // Format the date to be used in the input fields
    var dd = String(today.getDate()).padStart(2, '0');
    var mm = String(today.getMonth() + 1).padStart(2, '0'); // January is 0!
    var yyyy = today.getFullYear();
  
    today = yyyy + '-' + mm + '-' + dd;
  
    // Find all input elements with ID containing "due_date"
    var todaysDateInputs = document.querySelectorAll('input[id*="todays_date"]');
  
    // Set the default value for each found element
    todaysDateInputs.forEach(function(input) {
      input.value = today;
    });
  </script>

<div id="empty-form" style="display:none;">


    <div class="form-group">
        <label for="id_steps-__prefix__-assigned_to">Assigned to:</label>
        <select name="steps-__prefix__-assigned_to" id="steps-__prefix__-assigned_to" class="form-control">
            <option value="" selected disabled>Choose a worker</option>
            {% for user in users %}
            <option value="{{ user.username }}">{{ user.username }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="id_steps-__prefix__-todays_date">Today's Date</label>
        <input type="date" name="steps-__prefix__-todays_date" id="id_steps-__prefix__-todays_date" class="form-control">
    </div>

        <div class="form-row">
            <div class="form-group">
                <label for="id_steps-__prefix__-file">Picture 9am:</label>
                <input type="file" name="steps-__prefix__-file" id="id_steps-__prefix__-file" class="form-control">
            </div>
            <div class="form-group">
                <label for="id_steps-__prefix__-file2">Picture 11am:</label>
                <input type="file" name="steps-__prefix__-file2" id="id_steps-__prefix__-file2" class="form-control">
            </div>
            <div class="form-group">
                <label for="id_steps-__prefix__-file3">Picture 1pm:</label>
                <input type="file" name="steps-__prefix__-file3" id="id_steps-__prefix__-file3" class="form-control">
            </div>
            <div class="form-group">
                <label for="id_steps-__prefix__-file4">Picture End:</label>
                <input type="file" name="steps-__prefix__-file4" id="id_steps-__prefix__-file4" class="form-control">
            </div>
        </div>


    <div class="form-group">
        <label for="id_steps-__prefix__-sign_sheet">Sign job sheet:</label>
        <input type="file" name="steps-__prefix__-sign_sheet" id="id_steps-__prefix__-sign_sheet" class="form-control">
    </div>

    <div class="form-group">
        <label for="id_steps-__prefix__-description">Additional Comments</label>
        <textarea name="steps-__prefix__-description" cols="40" rows="10" id="id_steps-__prefix__-description" class="form-control"> </textarea>
    </div>


</div>
<style>

    .register-form-container {
        
    }
    .navbar {
        background-color: #333;
        display: flex;
        justify-content: space-between;
        padding: 10px 20px;
        align-items: center;
        margin-bottom: 50px;
    }

    .navbar a {
        color: white;
        text-decoration: none;
        margin: 0 5px;
        padding: 8px 12px;
        border-radius: 5px;
    }

    .navbar p {
        color: white;
        margin: 0;
        font-weight: bold;
    }
    body {
        background-color: #f2f2f2;
        margin: 0;
        padding: 0;
    }

    break-container{
        background-color: #f2f2f2;
        padding: 20px;
        border: 1px solid #dbdbdb;
        border-radius: 10px;
    } 
   
        /* Your additional CSS styles specific to create_project.html */
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        input[type="file"] {
            width: 100px; /* Adjust the width as needed */
            border-radius: 4px; /* Optional: Rounds the corners */
        }
        
    
        .register-form-container {
            background-color: #ffffff;
            border: 1px solid #dbdbdb;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
        }
    
        .form-group {
            margin-bottom: 20px;
            flex: 1; /* Each form group takes equal width */
            min-width: 0; 
        }
        .form-row {
            display: flex;
            justify-content: space-between; /* Distributes space between the form groups */
            gap: 20px; /* Adjust the gap between the form groups */
        }
    
        .form-group label {
            font-weight: bold;
            margin-bottom: 5px;
            display: block;
        }
    
        input[type="text"],
        input[type="email"],
        input[type="password"],
        textarea,
        select {
            width: 100%;
            padding: 10px;
            border: 1px solid #dbdbdb;
            border-radius: 5px;
            box-sizing: border-box; /* Ensures padding and border are included in the width */
        }
    
        /* Add margin-bottom for each form element to create spacing between them */
        input[type="text"],
        input[type="email"],
        input[type="password"],
        textarea,
        select {
            margin-bottom: 10px;
        }
    
        .btn-primary {
            background-color: #8a00b8;
            color: #ffffff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
    
        .login-link {
            text-align: center;
            margin-top: 20px;
        }
    
        .login-link a {
            color: #8a00b8;
            text-decoration: none;
        }

        input[type="date"] {
            appearance: none; /* Hide the default appearance of the input */
            background-color: #ffffff;
            border: 1px solid #dbdbdb;
            border-radius: 5px;
            padding: 10px;
        }
    
        /* Optional: Set the width to fit your form layout */
        input[type="date"] {
            width: 100%;
        }
    
</style>
{% endblock %}